* Revision

  This gem automates incrementing multi-component revision IDs for C makefile projects.
  It prompts for a change history entry associated with each increment and embeds it in a source file comment, formatted for extraction during archiving.

  It can also be used to rebuild and archive the current revision.

** Installation

   #+BEGIN_NOTE
   The gem hasn't been uploaded to rubygems.org as yet.
   #+END_NOTE

*** From rubygems.org

    #+BEGIN_SRC sh
      gem install revision
    #+END_SRC

*** From source

    #+BEGIN_SRC sh
      gem install bundler
      git clone git@git.nmd.ie:gem/revision
      cd revision
      bundle install
      bundle exec rake install
    #+END_SRC

** Usage

   Run the executable with no arguments to get usage instructions in your console window...

   #+BEGIN_SRC sh
     revision
   #+END_SRC

** Development

   After checking out the repo, run =bin/setup= to install dependencies. Then, run =rake spec= to run the tests. You can also run =bin/console= for an interactive prompt that will allow you to experiment.

   To install this gem onto your local machine, run =bundle exec rake install=. To release a new version, update the version number in =version.rb=, and then run =bundle exec rake release=, which will create a git tag for the version, push git commits and tags, and push the =.gem= file to [rubygems.org](https://rubygems.org).

** Improvements
   Refactor bootloader-related complexity out of ~Revision::Releasable~ and ~Revision::Info~
   Instead, releasable and revisioninfo should expect simple flat structure, and coordination should happen at higher
   (CLI) level.

   - Releasable name: defaults to <root folder name> -- overridable
   - Releasable rev_history file: defaults to <name>Revision.c -- overrideable (e.g. to have CD bootloader release update firmware revision history)

#+BEGIN_SRC
:releasables:
  - :id: firmware_bootloadable
    :revision_src: src/FirmwareRevision.c
    :build_steps:
      - make -F Makefile CONF=bootloadable
    :artefacts:
      - :src: dist/bootloadable/production/firmware.production.hex
        :dest: firmware_bootloadable_<REV>.hex
  - :id: firmware_standalone
    :revision_src: src/FirmwareRevision.c
    :build_steps:
      - make -F Makefile CONF=default
    :artefacts:
      - :src: dist/default/production/firmware.production.hex
        :dest: firmware_standalone_<REV>.hex
#+END_SRC

#+BEGIN_SRC
:releasables:
  - :id: bootloader_standalone
    :revision_src: ../firmware/src/FirmwareRevision.c
    :build_steps:
      - make -F Makefile CONF=default
    :artefacts:
      - :src: dist/default/production/bootloader.production.hex
        :dest: bootloader_standalone_<REV>.hex
        :zip: false
  - :id: bootloader_unified
    :revision_src: ../firmware/src/FirmwareRevision.c
    :build_steps:
      - make -F Makefile CONF=default
    :artefacts:
      - :src: dist/default/production/bootloader.production.hex
        :dest: bootloader_standalone_<REV>.hex
        :zip: false
#+END_SRC

#+BEGIN_SRC
:releasables:
  - :folder: firmware
  - :folder: bootloader
#+END_SRC

   Top level CLI -- supports project level .releasables
   similar syntax to that used in statemachine gem, e.g.



** Contributing

   Bug reports and pull requests are welcome on GitHub at https://github.com/[USERNAME]/revision.
